### ISSUE TITLE
API Features

### ISSUE THREAD

**Issue by immanuelhume** [nelsonchoo456/RC4LaundryBot2021#1]
## To-dos

- [x] refactor: validation for `Machine.floor` and `Machine.pos`
    - else, don't validate at all and return 404
- [x] refactor: move database URL into environment variable
- [x] fix: PyDantic subclasses do not inherit OpenAPI metadata
- [x] fix: `WithOptionalFields` cannot affect indirect superclasses
- [x] feat: finish endpoints for records
- [x] feat: authentication for POST/PUT endpoints
- [ ] feat: add sort and limit params to endpoints which return a list of resources
- [x] feat: add `approx_time_remaining` field to machine.Machine
  - this will require separation of db model and dto model
- [ ] test: integration tests for /machine/search endpoint
- [x] ci: try terraform/docker for deployment
  - See https://github.com/robmorgan/terraform-cloudrun-example
- [ ] ci: figure out how to do migrations with sqlalchemy
- [x] chore: add proper docstrings
- [x] fix: some code duplication for PyDantic fields
- [x] feat: model for raspi
  - need `floor`, `pos`, and `ip_addr` fields
- [ ] chore: use a cleaner init/shutdown func
  - see https://fastapi.tiangolo.com/advanced/events/
- [x] chore: shift all env and config things into PyDantic BaseSettings
  - see https://fastapi.tiangolo.com/advanced/settings/#pydantic-settings
- [x] chore: change `is_in_use` to `state` enum
  - in_use; idle; error
- [x] feat: add upsert endpoint for raspi
- [ ] feat: add `updated_on` field for raspi
- [ ] feat: time started and time stopped for each usage record
  - else, time ran
